create table authorities (
    user_id int8 not null,
    authorities varchar(255)
);

create table messages (
    id int8 generated by default as identity,
    description varchar(2048) not null,
    user_id int8 not null,
    primary key (id)
);

create table users (
    user_id int8 generated by default as identity,
    activation_code varchar(255),
    birth_date varchar(255),
    email varchar(255),
    image_name varchar(255),
    number int4 default 0,
    password varchar(255) not null,
    username varchar(255) not null unique,
    primary key (user_id)
);

alter table if exists authorities
    add constraint authorities_user_fk
    foreign key (user_id) references users;

alter table if exists messages
    add constraint message_user_fk
    foreign key (user_id) references users